sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
  - '5'
  - '4'
before_script:
  - npm prune
script:
  - npm test

after_success:
  - npm run coverage

branches:
  only:
    - master
    - /^greenkeeper-.*$/
